services:
  cache:
    image: redis:7.2.5-alpine
    container_name: cache-redis-db
    restart: always
    ports:
      - 6379:6379
    mem_limit: 512mb
    volumes:
      - ./compose/data/caches:/data
    networks:
      - localnet

  bucket:
    image: bitnami/minio:2024.8.3
    container_name: bucket-minio-db
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    mem_limit: 1Gb
    cpu_percent: 5
    volumes:
      - ./compose/data/buckets:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=viva-sabor
      - MINIO_ROOT_PASSWORD=Viva_Sabor@123
      - MINIO_DEFAULT_BUCKETS='images,videos'
    networks:
      - localnet

  # bucket-client:
  #   image: bitnami/minio-client:2024.7.31
  #   container_name: bucket-minio-client
  #   restart: always
  #   mem_limit: 512mb
  #   cpu_percent: 5
  #   depends_on:
  #     - bucket
  #   # volumes:
  #   #   - ./compose/data/buckets:/
  #   environment:
  #     - MINIO_SERVER_ROOT_USER=viva-sabor
  #     - MINIO_SERVER_ROOT_PASSWORD=Viva_Sabor@123
  #   networks:
  #     - localnet

  nosql:
    image: mongo:7.0.13-rc0-jammy
    container_name: document-mongo-db
    restart: always
    ports:
      - 27017:27017
    mem_limit: 512mb
    cpu_percent: 5
    volumes:
      - ./compose/data/documents:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME:viva-sabor
      - MONGO_INITDB_ROOT_PASSWORD:Viva_Sabor_123
    networks:
      - localnet

  sql:
    image: postgres:15.2-alpine3.17
    container_name: sql-postgre-db
    restart: always
    ports:
      - 5432:5432
    mem_limit: 512mb
    volumes:
      - ./compose/data/sqls:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=vivasabor
      - POSTGRES_USER=viva-sabor
      - POSTGRES_PASSWORD=Viva_Sabor@123
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
